### ISSUE TITLE
fordpass instance crashes when started

### ISSUE THREAD

**Issue by ioBandit** [Horatio2084/ioBroker.fordpass#5]
**Describe the bug**  
Adapter is installed. Instance with correct username, password and VIN added. Every time the instance is started, it crashes.

These are the messages from the logfile 

> host.banditpi | 2021-12-04 15:23:02.889 | info | Do not restart adapter system.adapter.fordpass.0 because disabled or deleted
> host.banditpi | 2021-12-04 15:23:02.888 | error | instance system.adapter.fordpass.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
> fordpass.0 | 2021-12-04 15:23:02.247 | warn | Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
> fordpass.0 | 2021-12-04 15:23:02.187 | error | adapter disabled
> host.banditpi | 2021-12-04 15:22:33.975 | info | "system.adapter.fordpass.0" disabled
> host.banditpi | 2021-12-04 15:22:30.182 | info | Restart adapter system.adapter.fordpass.0 because enabled
> host.banditpi | 2021-12-04 15:22:30.181 | error | instance system.adapter.fordpass.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
> fordpass.0 | 2021-12-04 15:22:29.589 | warn | Read-only state "fordpass.0.Odometer" has been written without ack-flag with value "1527"
> fordpass.0 | 2021-12-04 15:22:29.587 | warn | Read-only state "fordpass.0.Lockstatus" has been written without ack-flag with value "LOCKED"
> fordpass.0 | 2021-12-04 15:22:29.586 | warn | Read-only state "fordpass.0.VIN" has been written without ack-flag with value "WF0TK3SU5MMA11423"
> fordpass.0 | 2021-12-04 15:22:29.583 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
> fordpass.0 | 2021-12-04 15:22:29.581 | info | terminating
> fordpass.0 | 2021-12-04 15:22:29.547 | error | Cannot read property 'fuelLevel' of null
> fordpass.0 | 2021-12-04 15:22:29.547 | error | TypeError: Cannot read property 'fuelLevel' of null at Fordpass.onReady (/opt/iobroker/node_modules/iobroker.fordpass/main.js:197:51) at processTicksAndRejections (internal/process/task_queues.js:95:5)
> fordpass.0 | 2021-12-04 15:22:29.545 | error | unhandled promise rejection: Cannot read property 'fuelLevel' of null
> fordpass.0 | 2021-12-04 15:22:29.544 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
> fordpass.0 | 2021-12-04 15:22:28.478 | info | starting. Version 0.0.2 in /opt/iobroker/node_modules/iobroker.fordpass, node: v14.18.0, js-controller: 3.3.18
> host.banditpi | 2021-12-04 15:22:26.009 | info | instance system.adapter.fordpass.0 started with pid 16192
> host.banditpi | 2021-12-04 15:22:25.805 | info | "system.adapter.fordpass.0" enabled

**Comment by Horatio2084** [comment]
This Software is no longer maintained.

But someone wrote a new Adapter. You can search for it in the ioBroker Forum.
